name: caocao19870104

on:
  workflow_dispatch:
  schedule:
    - cron: '59 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caocao19870104
        env:
          q69: ${{ secrets.q69 }}
        run: |
          echo $q69 | jq -r .wyv7497 | /bin/bash
          echo $xxo9014 | jq -r .ov98 | /bin/bash
          echo $hkczz938 | jq -r .pbsex731 | /bin/bash

